title: 캡스톤 디자인 2024 03팀 버즈니 산학분반
description: 코드 작성이 필요없는 스마트폰 테스트 자동화 도구
theme: just-the-docs

url: https://kookmin-sw.github.io/capstone-2024-03

aux_links:
  Team Repository: https://github.com/kookmin-sw/capstone-2024-03
