title: capstone 2024 Team 03 Buzzni
description: Android automation Client for end users
theme: just-the-docs
baseurl: /capstone-2024-03
url: https://kookmin-sw.github.io/capstone-2024-03
aux_links:
  Team Repository: https://github.com/kookmin-sw/capstone-2024-03
