version: "3.8"

services:
    api:
        build:
            context: ./
            dockerfile: docker/Dockerfile.python
        container_name: api
        restart: always
        expose:
            - 5000:5000
