version: "3.8"

services:
    api:
        build:
            context: ./
            dockerfile: docker/Dockerfile.python
        container_name: api
        restart: always
        expose:
            - 5000:5000

    nginx:
        build:
            context: ./
            dockerfile: docker/Dockerfile.nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"